### PR TITLE
(fix) allow yml as well as yaml extension to be used with edgex-publish-swagger

### LINKED ISSUE #237: edgex-publish-swagger.sh accepts only *.yaml files and not *.yml
Developers had to rename swagger API files from .yml to .yaml to get past this.  Would be nice to accept both:
https://github.com/edgexfoundry/app-functions-sdk-go/pull/465/files

16:52:18  --> edgex-publish-swagger.sh
16:52:18  === Publish openapi/v2 API ===
16:52:18  [publishToSwagger] Publishing the API Docs [openapi/v2] to Swagger
16:52:18  cat: /w/workspace/ndry_app-functions-sdk-go_master/openapi/v2/*.yaml: No such file or directory
[Pipeline] }
16:52:18  Deleting 1 temporary files

https://github.com/edgexfoundry/edgex-global-pipelines/blob/master/resources/edgex-publish-swagger.sh#L21-L23

### PR DESCRIPTION
**Pull request by bill-mahoney**
(fix) allow yml as well as yaml extension to be used with edgex-publish-swagger

Signed-off-by: Bill Mahoney <bill.mahoney@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/edgexfoundry/ci-management/blob/master/.github/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Added labels
## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Issue Number:
#237 
## Sandbox Testing
Test Links :

## Other information

Closes #237

### CODE REVIEW

**Review by ernestojeda — APPROVED** [review]
LGTM

File: resources/edgex-publish-swagger.sh [hunk 1]
```diff
@@ -1,5 +1,5 @@
 #!/bin/bash
-
+shopt -s extglob
```
Comment (ernestojeda) [inline resources/edgex-publish-swagger.sh:2]: I did not know about this. Nice
